repositories {
    mavenLocal()
    mavenCentral()

    maven { // Jade
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { // JEI
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven { // Registrate
        url "https://maven.gegy.dev/releases"
    }
    maven {// LDLib
        name "firstdarkdev"
        url "https://maven.firstdarkdev.xyz/snapshots"
    }
}