dependencies {
    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.neoforge.api) { transitive = false }
    compileClasspath(libs.jei.neoforge) { transitive = false }
    runtimeClasspath(libs.jei.neoforge) { transitive = false }

    // Jade
    compileClasspath(libs.jade)
    runtimeClasspath(libs.jade)

    // Registrate
    api(libs.registrate)
    jarJar(libs.registrate)

    // LDLib2
    implementation(libs.lidlib2)

    // AppEng
    implementation(libs.appeng)
}
