# Jvm info
java_version=25
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

# Mod info
mod_id=noway_core
mod_name=NoWay Core
mod_description=NoWay
mod_license=GPL-3.0
mod_version=0.0.2
mod_url=https://github.com/TeameWay/NoWay-Core

# Development info
maven_group=com.teameway

minecraft_version_range=[26.1,26.2)
neo_version_range=[26.1.0.0-beta,)

# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)
