[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.107"
jei = "29.37.0.98"
jade = "26.1.1+neoforge"
modDevGradle = "2.0.141"
lombok = "8.7.1"
registrate = "MC26.1-1.5.7"
ldlib2 = "26.1.2.39"
appeng = "26.1.11-beta"

[libraries]
jei-common-api = { group = "mezz.jei", name = "jei-26.1.2-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-26.1.2-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-26.1.2-neoforge", version.ref = "jei" }
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
lidlib2 = { group = "com.lowdragmc.ldlib2", name = "ldlib2-neoforge-26.1", version.ref = "ldlib2" }
appeng = { group = "org.appliedenergistics", name = "appliedenergistics2", version.ref = "appeng" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
